FFNN = read.csv("FFNN.csv")
RBFN = read.csv("RBFNN.csv")

pdf("FFNN.pdf")
plot(range((0:dim(FFNN)[1])), range(FFNN), type="n", ylab="NN Outputs and Desired Output", xlab="Iterations", main="Multilayer Perceptron Neural Network Example")
lines(FFNN$NN1.Answer, type="l", lwd=10, col='blue')
lines(FFNN$NN2.Answer, type="l", lwd=10, col='red')
lines(FFNN$NN3.Answer, type="l", lwd=10, col='yellow')
lines(FFNN$NN1.Output, type="l", lwd=5, col='purple') 
lines(FFNN$NN2.Output, type="l", lwd=5, col='orange') 
lines(FFNN$NN3.Output, type="l", lwd=5, col='green') 
legend(0.8*dim(FFNN)[1],0.85*range(FFNN)[2],c('D1','D2','D3','O1','O2','O3'),col=c('blue','red','yellow','purple','orange','green'),lwd=5)
dev.off()

pdf("RBFN.pdf")
plot(range((0:dim(RBFN)[1])), range(RBFN), type="n", ylab="NN Outputs and Desired Output", xlab="Iterations", main="Radial Basis Function Neural Network Example")
lines(RBFN$NN1.Answer, type="l", lwd=10, col='blue')
lines(RBFN$NN2.Answer, type="l", lwd=10, col='red')
lines(RBFN$NN3.Answer, type="l", lwd=10, col='yellow')
lines(RBFN$NN1.Output, type="l", lwd=5, col='purple') 
lines(RBFN$NN2.Output, type="l", lwd=5, col='orange') 
lines(RBFN$NN3.Output, type="l", lwd=5, col='green') 
legend(0.8*dim(RBFN)[1],0.85*range(RBFN)[2],c('D1','D2','D3','O1','O2','O3'),col=c('blue','red','yellow','purple','orange','green'),lwd=5)
dev.off()
